#pragma once

typedef enum {
	BT_JINJO_WHITE,
	BT_JINJO_ORANGE,
	BT_JINJO_YELLOW,
	BT_JINJO_BROWN,
	BT_JINJO_GREEN,
	BT_JINJO_RED,
	BT_JINJO_BLUE,
	BT_JINJO_PURPLE,
	BT_JINJO_BLACK,
	BT_JINJO_MAX,
} bt_jinjo_t;
