#ifndef BT_MAP_HPP
    #define BT_MAP_HPP

    #include <iostream>
    #include <map>
    #include <string>
    #include <vector>
    #include <archipelago.h>
    #include <bt/save_flags.h>
    #include <usb/usb_com.hpp>

    extern std::map<uint16_t, std::map<std::string, std::vector<std::string>>> ASSET_MAP_CHECK;
    // const std::map<std::string, std::string> ADDRESS_MAP;
    bool check_flag(std::string);

    typedef struct {
        int mapId;
        int from_map;
        int entranceId;
        int exitId;
    } world_entrance_t;

    extern std::map<std::string, world_entrance_t> WORLD_ENTRANCES;
    enum {
        BT_ZOOMBOX_ICON_GLOWBO,
        BT_ZOOMBOX_ICON_JIGGY,
        BT_ZOOMBOX_ICON_HONEYCOMB,
        BT_ZOOMBOX_ICON_SUB,
        BT_ZOOMBOX_ICON_WASHER,
        BT_ZOOMBOX_ICON_BANJO,
        BT_ZOOMBOX_ICON_KAZOOIE,
        BT_ZOOMBOX_ICON_BOTTLES,
        BT_ZOOMBOX_ICON_MUMBO,
        BT_ZOOMBOX_ICON_JINJO_YELLOW,
        BT_ZOOMBOX_ICON_JINJO_GREEN,
        BT_ZOOMBOX_ICON_JINJO_BLUE,
        BT_ZOOMBOX_ICON_JINJO_PURPLE,
        BT_ZOOMBOX_ICON_JINJO_ORANGE,
        BT_ZOOMBOX_ICON_BEEHIVE,
        BT_ZOOMBOX_ICON_GRUNTY,
        BT_ZOOMBOX_ICON_ZUBBA,
        BT_ZOOMBOX_ICON_JAMJARS,
        BT_ZOOMBOX_ICON_BOVINA,
        BT_ZOOMBOX_ICON_MINJO_WHITE,
        BT_ZOOMBOX_ICON_MINJO_ORANGE,
        BT_ZOOMBOX_ICON_MINJO_YELLOW,
        BT_ZOOMBOX_ICON_MINJO_BROWN,
        BT_ZOOMBOX_ICON_UNOGOPAZ,
        BT_ZOOMBOX_ICON_CHIEF_BLOATAZIN,
        BT_ZOOMBOX_ICON_DILBERTA,
        BT_ZOOMBOX_ICON_STONIES1,
        BT_ZOOMBOX_ICON_CANARY_MARY,
        BT_ZOOMBOX_ICON_CHEATO,
        BT_ZOOMBOX_ICON_GOBI,
        BT_ZOOMBOX_ICON_DINO_KID1,
        BT_ZOOMBOX_ICON_MR_PATCH,
        BT_ZOOMBOX_ICON_MOGGY,
        BT_ZOOMBOX_ICON_SOGGY,
        BT_ZOOMBOX_ICON_GROGGY,
        BT_ZOOMBOX_ICON_MRS_BOGGY,
        BT_ZOOMBOX_ICON_PROSPECTOR,
        BT_ZOOMBOX_ICON_HUMBA,
        BT_ZOOMBOX_ICON_UFO,
        BT_ZOOMBOX_ICON_OLD_KING_COAL,
        BT_ZOOMBOX_ICON_SSSLUMBER,
        BT_ZOOMBOX_ICON_BOGGY,
        BT_ZOOMBOX_ICON_BIG_AL,
        BT_ZOOMBOX_ICON_SALTY_JOE,
        BT_ZOOMBOX_ICON_CONGA,
        BT_ZOOMBOX_ICON_PAWNO,
        BT_ZOOMBOX_ICON_TIPTUP,
        BT_ZOOMBOX_ICON_JOLLY,
        BT_ZOOMBOX_ICON_MERRY_MAGGIE,
        BT_ZOOMBOX_ICON_TERRY,
        BT_ZOOMBOX_ICON_BARGASAURUS,
        BT_ZOOMBOX_ICON_YELLOW_STONY,
        BT_ZOOMBOX_ICON_ALIEN,
        BT_ZOOMBOX_ICON_CHRIS_P_BACON,
        BT_ZOOMBOX_ICON_CAPTAIN_BLUBBER,
        BT_ZOOMBOX_ICON_STYRACOSAURUS_MOM,
        BT_ZOOMBOX_ICON_ROYSTEN,
        BT_ZOOMBOX_ICON_SAFE,
        BT_ZOOMBOX_ICON_GUFFO,
        BT_ZOOMBOX_ICON_MR_FIT,
        BT_ZOOMBOX_ICON_CAPTAIN_BLACKEYE,
        BT_ZOOMBOX_ICON_JINJO_RED,
        BT_ZOOMBOX_ICON_JINJO_WHITE,
        BT_ZOOMBOX_ICON_JINJO_BLACK,
        BT_ZOOMBOX_ICON_JINJO_BROWN,
        BT_ZOOMBOX_ICON_CHILLY_WILLY,
        BT_ZOOMBOX_ICON_CHILLI_BILLI,
        BT_ZOOMBOX_ICON_MINGY_JONGO,
        BT_ZOOMBOX_ICON_YELLOW_DODGEM,
        BT_ZOOMBOX_ICON_MINGELLA,
        BT_ZOOMBOX_ICON_BLOBBELDA,
        BT_ZOOMBOX_ICON_KLUNGO,
        BT_ZOOMBOX_ICON_BOTTLES_DEAD,
        BT_ZOOMBOX_ICON_MINJO_GREEN,
        BT_ZOOMBOX_ICON_MINJO_RED,
        BT_ZOOMBOX_ICON_MINJO_BLUE,
        BT_ZOOMBOX_ICON_MINJO_PURPLE,
        BT_ZOOMBOX_ICON_MINJO_BLACK,
        BT_ZOOMBOX_ICON_RABBIT_WORKER1,
        BT_ZOOMBOX_ICON_UNGA_BUNGA,
        BT_ZOOMBOX_ICON_JIGGYWIGGY,
        BT_ZOOMBOX_ICON_JIGGYWIGGY_DISCIPLE,
        BT_ZOOMBOX_ICON_HONEY_B,
        BT_ZOOMBOX_ICON_BANJO_KAZOOIE,
        BT_ZOOMBOX_ICON_PIG1,
        BT_ZOOMBOX_ICON_OOGLE_BOOGLE,
        BT_ZOOMBOX_ICON_GI_ANNOUNCER,
        BT_ZOOMBOX_ICON_DINGPOT,
        BT_ZOOMBOX_ICON_KING_JINGALING_DEAD,
        BT_ZOOMBOX_ICON_ROCKNUT,
        BT_ZOOMBOX_ICON_MILDRED,
        BT_ZOOMBOX_ICON_BIGGA_FOOT,
        BT_ZOOMBOX_ICON_GEORGE,
        BT_ZOOMBOX_ICON_SABREMAN,
        BT_ZOOMBOX_ICON_DIPPY,
        BT_ZOOMBOX_ICON_LOGGO,
        BT_ZOOMBOX_ICON_KING_JINGALING,
        BT_ZOOMBOX_ICON_MRS_BOTTLES,
        BT_ZOOMBOX_ICON_SPECCY,
        BT_ZOOMBOX_ICON_GOGGLES,
        BT_ZOOMBOX_ICON_TARGITZAN,
        BT_ZOOMBOX_ICON_CHOMPA,
        BT_ZOOMBOX_ICON_LORD_WOO_FAK_FAK,
        BT_ZOOMBOX_ICON_WELDAR,
        BT_ZOOMBOX_ICON_ALIEN_CHILD,
        BT_ZOOMBOX_ICON_EVIL_BOTTLES,
        BT_ZOOMBOX_ICON_DINO_KID2,
        BT_ZOOMBOX_ICON_DINO_SCRIT_SMALL,
        BT_ZOOMBOX_ICON_DINO_SCRIT_BIG,
        BT_ZOOMBOX_ICON_HEGGY,
    };

#endif
