#ifndef AP_MEMORY_ITEMS_H
#define AP_MEMORY_ITEMS_H

enum {
  AP_ITEM_PAGES,
  AP_ITEM_HONEY,
  AP_ITEM_WJINJO,
  AP_ITEM_OJINJO,
  AP_ITEM_YJINJO,
  AP_ITEM_BRJINJO,
  AP_ITEM_GJINJO,
  AP_ITEM_RJINJO,
  AP_ITEM_BLJINJO,
  AP_ITEM_PJINJO,
  AP_ITEM_BKJINJO,
  AP_ITEM_DOUBLOON,
  AP_ITEM_JIGGY,
  AP_ITEM_TREBLE,
  AP_ITEM_NOTE,
  AP_ITEM_MUMBOTOKEN,
  AP_ITEM_IKEY,
  AP_ITEM_PMEGG,
  AP_ITEM_BMEGG,


  AP_ITEM_GGRAB,
  AP_ITEM_BBLASTER,
  AP_ITEM_EGGAIM,
  AP_ITEM_BDRILL,
  AP_ITEM_BBAYONET,
  AP_ITEM_AIREAIM,
  AP_ITEM_SPLITUP,
  AP_ITEM_WWHACK,
  AP_ITEM_TTORP,
  AP_ITEM_AUQAIM,
  AP_ITEM_SHPACK,
  AP_ITEM_GLIDE,
  AP_ITEM_SNPACK,
  AP_ITEM_LSPRING,
  AP_ITEM_CLAWBTS,
  AP_ITEM_SPRINGB,
  AP_ITEM_TAXPACK,
  AP_ITEM_HATCH,
  AP_ITEM_PACKWH,
  AP_ITEM_SAPACK,
  AP_ITEM_FEGGS,
  AP_ITEM_GEGGS,
  AP_ITEM_CEGGS,
  AP_ITEM_IEGGS,
  AP_ITEM_FSWIM,
  AP_ITEM_DAIR,
  AP_ITEM_BBASH,
  AP_ITEM_HOMINGEGGS,
  AP_ITEM_AMAZEOGAZE,
  AP_ITEM_ROAR,

  AP_ITEM_DIVE,
  AP_ITEM_FPAD,
  AP_ITEM_GRAT,
  AP_ITEM_ROLL,
  AP_ITEM_ARAT,
  AP_ITEM_BBARGE,
  AP_ITEM_TJUMP,
  AP_ITEM_FLUTTER,
  AP_ITEM_FFLIP,
  AP_ITEM_CLIMB,
  AP_ITEM_BEGGS,
  AP_ITEM_TTROT,
  AP_ITEM_BBUST,
  AP_ITEM_WWING,
  AP_ITEM_SSTRIDE,
  AP_ITEM_TTRAIN,
  AP_ITEM_BBOMB,
  AP_ITEM_EGGSHOOT,

  // Mumbo Magics
  AP_ITEM_MUMBOMT,
  AP_ITEM_MUMBOGM,
  AP_ITEM_MUMBOWW,
  AP_ITEM_MUMBOJR,
  AP_ITEM_MUMBOTD,
  AP_ITEM_MUMBOGI,
  AP_ITEM_MUMBOHP,
  AP_ITEM_MUMBOCC,
  AP_ITEM_MUMBOIH,

  AP_ITEM_HUMBAMT,
  AP_ITEM_HUMBAGM,
  AP_ITEM_HUMBAWW,
  AP_ITEM_HUMBAJR,
  AP_ITEM_HUMBATD,
  AP_ITEM_HUMBAGI,
  AP_ITEM_HUMBAHP,
  AP_ITEM_HUMBACC,
  AP_ITEM_HUMBAIH,

  //Train Switches
  AP_ITEM_TRAINSWIH,
  AP_ITEM_TRAINSWTD,
  AP_ITEM_TRAINSWGI,
  AP_ITEM_TRAINSWHP1,
  AP_ITEM_TRAINSWHP2,
  AP_ITEM_TRAINSWWW,

  AP_ITEM_CHUFFY,

  // junk
  AP_ITEM_GNEST,
  AP_ITEM_ENEST,
  AP_ITEM_FNEST,

  //event items
  AP_ITEM_MTA,
  AP_ITEM_GGA,
  AP_ITEM_WWA,
  AP_ITEM_JRA,
  AP_ITEM_TDA,
  AP_ITEM_GIA,
  AP_ITEM_HFA,
  AP_ITEM_CCA,
  AP_ITEM_CKA,
  AP_ITEM_H1A,

  AP_ITEM_MAX, // needs to be last
};

enum {
  AP_SILO_JINJO_VILLAGE,
  AP_SILO_WOODED_HOLLOW,
  AP_SILO_PLATEAU,
  AP_SILO_PINE_GROVE,
  AP_SILO_CLIFF_TOP,
  AP_SILO_WASTELAND,
  AP_SILO_QUAGMIRE,
  AP_SILO_MAX,
};

enum {
  AP_TRAP_TRIP,
  AP_TRAP_SLIP,
  AP_TRAP_MISFIRE,
  AP_TRAP_SQUISH,

  AP_TRAP_MAX,
};

#endif // AP_MEMORY_ITEMS_H
